name: 'Discord Notifier'

description: 'Send message notifications to Discord'

inputs:
    webhookUrl:
        description: 'Discord Webhook URL'
        required: true
    status:
        description: 'Status of the build'
        required: true
    projectName:
        description: 'Name of the project'
        required: true
    testResultsUrl:
        description: 'URL to test results'
        required: false
    sonarProjectKey:
        description: 'SonarCloud project key'
        required: false
    sonarQualityGateStatus:
        description: 'Status of the SonarCloud Quality Gate'
        required: false
    username:
        description: 'Username to display in the message'
        required: false
    avatarUrl:
        description: 'URL to the avatar image'
        required: false

runs:
    using: 'node20'
    main: 'dist/main.js'
